# Generated by Django 4.1.3 on 2022-12-18 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first", models.CharField(default="Null", max_length=64)),
                ("middle", models.CharField(default="Null", max_length=64)),
                ("last", models.CharField(default="Null", max_length=64)),
                ("tel", models.CharField(default="Null", max_length=64)),
                ("tel2", models.CharField(default="Null", max_length=64)),
                ("address", models.CharField(default="Null", max_length=200)),
                ("email", models.CharField(default="Null", max_length=100)),
                ("email2", models.CharField(default="Null", max_length=100)),
                ("website", models.CharField(default="Null", max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content_title", models.CharField(max_length=100)),
                ("content_description", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="ContentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content_type", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first", models.CharField(default="Null", max_length=64)),
                ("middle", models.CharField(default="Null", max_length=64)),
                ("last", models.CharField(default="Null", max_length=64)),
                ("position", models.CharField(default="Null", max_length=64)),
                ("address", models.CharField(default="Null", max_length=200)),
                ("email", models.CharField(default="Null", max_length=100)),
                ("email2", models.CharField(default="Null", max_length=100)),
                ("tel", models.CharField(default="Null", max_length=64)),
                ("tel2", models.CharField(default="Null", max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project", models.CharField(default="Null", max_length=100)),
                ("description", models.CharField(default="Null", max_length=250)),
                ("startingDate", models.DateField()),
                ("finishingDate", models.DateField()),
                (
                    "projectClient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_project",
                        to="one.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("proImage", models.CharField(default="Null", max_length=64)),
                ("proDescription", models.CharField(default="Null", max_length=200)),
                (
                    "project_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proImages",
                        to="one.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContentImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imageTitle", models.CharField(max_length=64)),
                ("imageDescription", models.CharField(max_length=64)),
                (
                    "img_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_image",
                        to="one.content",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="content",
            name="content_t",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contenttype",
                to="one.contenttype",
            ),
        ),
    ]
