# Generated by Django 4.1.3 on 2022-12-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("one", "0002_rename_project_project_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projectimage",
            old_name="proDescription",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="projectimage", old_name="proImage", new_name="imageTile",
        ),
        migrations.AddField(
            model_name="projectimage",
            name="image",
            field=models.ImageField(default="Null", upload_to="files/images"),
        ),
    ]
