# Generated by Django 4.1.3 on 2022-12-22 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("one", "0003_rename_prodescription_projectimage_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="projectimage", name="project_image",),
        migrations.AddField(
            model_name="projectimage",
            name="project",
            field=models.ForeignKey(
                
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project",
                to="one.project",
            ),
        ),
    ]
