# Generated by Django 4.1.3 on 2022-12-22 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("one", "0004_remove_projectimage_project_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="projectimage", name="project",),
        migrations.AddField(
            model_name="projectimage",
            name="project_image",
            field=models.ForeignKey(
                
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proImages",
                to="one.project",
            ),
        ),
    ]
