# Generated by Django 4.1.3 on 2022-12-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("one", "0007_alter_project_finishingdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectimage",
            name="image",
            field=models.ImageField(default="Null", upload_to="images/"),
        ),
    ]
