# Generated by Django 4.1.3 on 2022-12-22 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("one", "0009_contentimage_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contentimage", old_name="img_owner", new_name="content",
        ),
    ]
